### ISSUE TITLE
Issues in algo implementation.

### ISSUE THREAD

**Issue by stepancar** [parrker/karatsuba#1]
Hello!

Thank you for the article and your implementation.

I wanted to highlight some problems of this implementation

1) karatsuba was designed to support multiplication of long numbers, your implementation does not support it
2) in your implementation you multiply number by 10*n which is again quadratic operation if you don't use karatsuba
3) I see your https://github.com/parrker/karatsuba/blob/master/README.md says that people should not use your implementation, but it is not clear why exactly.

Thank you

**Comment by parrker** [comment]
Hi Stepan, thanks for your comment and your questions!

It has been a while since I created this repo. As I recall, I was just trying to get into algorithms and wanted to implement something in JavaScript, without any intention to actually use it. So, I would not treat this repo as anything more than an old playground.

The reason not to use this package is the fact that in JS you can just multiple two numbers using `*`, and this implementation will not give you a result that is better than that.

**Comment by stepancar** [comment]
@parrker , yeah , this totally make sense. Just wanted to leave this issue here so people who read your article and follow it trying to figure out how to implement it in javascript knew that they should try something else

**Comment by stepancar** [comment]
I wrote my implementation which supports long numbers and does not multiply by 10^n
https://github.com/stepancar/dsaa/blob/main/algorithms/karatsuba/index.js
But for now, my implementation is still very basic too, because I use an array and sometimes push leading zeros to front, which is O(n) operation. Also this implementation requires n log n memory. Which can be improved by introducing in-place modifications. Recursion should be replaced with stack to support really long numbers and maybe it would make sense to support other scales of notation
